rootProject.name = "tms-ktor-token-support"
include("token-support-idporten-sidecar")
include("token-support-idporten-sidecar-mock")
include("token-support-tokendings-exchange")
include("token-support-tokenx-validation")
include("token-support-tokenx-validation-mock")
include("token-support-azure-validation")
include("token-support-azure-validation-mock")
include("token-support-azure-exchange")
include("token-support-authentication-installer")
include("token-support-authentication-installer-mock")
