rootProject.name = "tms-ktor-token-support"
include("idporten-sidecar")
include("idporten-sidecar-mock")
include("tokendings-exchange")
include("tokenx-validation")
include("tokenx-validation-mock")
include("entra-id-validation")
include("entra-id-validation-mock")
include("entra-id-exchange")
include("user-token-verification")
include("user-token-verification-mock")
include("user-token-exchange")
