name: Bygg og publiser bibliotek for release
on:
  release:
    types:
      - published

permissions:
  packages: write

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Bygg bibliotek
        run:  ./gradlew build

      - name: Publish packages
        run: ./gradlew -Plib_version="${{ github.event.release.name }}" publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
